from dotenv import load_dotenv
import os

load_dotenv(override=True, verbose=True)

# POSTGRESQL DATABASE
_POSTGRES_HOST = os.getenv("POSTGRES_HOST")
_POSTGRES_PORT = os.getenv("POSTGRES_PORT")
_POSTGRES_USERNAME = os.getenv("POSTGRES_USERNAME")
_POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
assert _POSTGRES_HOST
assert _POSTGRES_PORT
assert _POSTGRES_USERNAME
assert _POSTGRES_PASSWORD
POSTGRES_HOST = _POSTGRES_HOST
POSTGRES_PORT = _POSTGRES_PORT
POSTGRES_USERNAME = _POSTGRES_USERNAME
POSTGRES_PASSWORD = _POSTGRES_PASSWORD

# ZYLA_API_KEY
_API_MARKET_KEY = os.getenv("API_MARKET_KEY")
assert _API_MARKET_KEY
API_MARKET_KEY = _API_MARKET_KEY